## MERGE function example

In [57]:
import pandas as pd

In [3]:
strickers_scores = pd.DataFrame({"players_name" : ["sanjay","shayam","harish","sridhar","lokesh","manoj"],
                                "players_scores" : [50,40,33,27,9,21]})
print(strickers_scores)

  players_name  players_scores
0       sanjay              50
1       shayam              40
2       harish              33
3      sridhar              27
4       lokesh               9
5        manoj              21

In [4]:
strickers2_scores = pd.DataFrame({"players_name" : ["vasanth","kumaran","pradeep","vicky","akash","narayanan"],
                                "players_scores" : [69,23,0,19,7,18]})
print(strickers2_scores)

  players_name  players_scores
0      vasanth              69
1      kumaran              23
2      pradeep               0
3        vicky              19
4        akash               7
5    narayanan              18

In [47]:
merged = strickers_scores.merge(
         strickers2_scores,how = 'inner')
print(merged)

Empty DataFrame
Columns: [players_name, players_scores]
Index: []

In [9]:
merged_table = pd.merge(
    strickers_scores, 
    strickers2_scores, 
    left_index=True, 
    right_index=True, 
    suffixes=('_Team1', '_Team2')
)
print(merged_table)

  players_name_Team1  players_scores_Team1 players_name_Team2  \
0             sanjay                    50            vasanth
1             shayam                    40            kumaran
2             harish                    33            pradeep
3            sridhar                    27              vicky
4             lokesh                     9              akash
5              manoj                    21          narayanan

   players_scores_Team2
0                    69
1                    23
2                     0
3                    19
4                     7
5                    18

In [7]:
merged = pd.merge(
    left=strickers_scores, 
    right=strickers2_scores, 
    left_index=True, 
    right_index=True, 
    suffixes=('_Team1', '_Team2')
)
merged

,players_name_Team1,players_scores_Team1,players_name_Team2,players_scores_Team2
0,sanjay,50,vasanth,69
1,shayam,40,kumaran,23
2,harish,33,pradeep,0
3,sridhar,27,vicky,19
4,lokesh,9,akash,7
5,manoj,21,narayanan,18

In [13]:
merged = pd.merge(
    strickers_scores, 
    strickers2_scores, 
    left_on='players_name', 
    right_on='players_scores', 
    how='inner'
)

print(merged)  ## Doubt - why output not showing with this command

ValueError: You are trying to merge on object and int64 columns for key 'players_name'. If you wish to proceed you should use pd.concat

## LIST comprention

In [24]:
## EX 1  
strickers2_scores

  players_name  players_scores
0      vasanth              69
1      kumaran              23
2      pradeep               0
3        vicky              19
4        akash               7
5    narayanan              18

In [21]:
strickers2_team = ["vasanth","kumaran","pradeep","vicky","akash","narayanan"]

new_players_list = [x for x in strickers2_scores if x != 'pradeep']

print(new_players_list)

['vasanth', 'kumaran', 'vicky', 'akash', 'narayanan']

In [39]:
## EX 2 :

strickers2 = ["vasanth","kumaran","pradeep","vicky","akash","narayanan"]
newplayers = [x for x in strickers2 if "i" in x]
print(newplayers)

['vicky']

## Lambda Function

In [45]:
## EX 1  - filter 

strickers2_scores["Result"]= strickers2_scores["players_scores"].apply(lambda x :"Qualified" if x>30 else "not Qualified" )

In [73]:
strickers2_scores

  players_name  players_scores         Result
0      vasanth              69      Qualified
1      kumaran              23  not Qualified
2      pradeep               0  not Qualified
3        vicky              19  not Qualified
4        akash               7  not Qualified
5    narayanan              18  not Qualified

In [91]:
players_name = ["vasanth","kumaran","pradeep","vicky","akash","narayanan"]

filtered_players = list(filter(lambda x: "y" in x,players_name))
print(filtered_players)

['vicky', 'narayanan']

In [98]:
players = ["Vasanth", "Kumaran", "Pradeep", "Vicky", "Akash"]
Y_team = list(filter(lambda name: name.endswith("y"), players))
print(Y_team)

['Vicky']

In [120]:
## EX 2  - map

name_list = ["Arun Kumar","Dinesh", "Santhosh Kumar","Moorthy", "Sanjay Kumar", 
                "Vasanth", "Kumaran", "Pradeep", "Vicky", "Akash", 
                "Narayanan", "Rahul", "Aditya", "Vikram", "Rohan", 
                "Mani", "Karthik", "Suresh", "Ramesh", "Ganesh",
                "Ashwin", "Madan", "Abhishek", "Vishal", "Nitin",
                "Prakash", "Amit", "Sunil", "Anil", "Varun",
                "Kiran", "Vivek", "Siddharth","Vijay Kumar", "Harish", 
                "Rajesh","Deepak Kumar", "Prabhu",  "Logesh", "Jeeva",
                "Bala", "Murugan", "Kathir", "Selvam", "Pandian",
                "Arvind", "Raghu", "Naveen", "Tharun", "Yuvraj"]

name_order = list(map(lambda Kumar: Kumar.endswith("Kumar"),name_list))
print(name_order)

[True, False, True, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False]

In [127]:
from functools import reduce

In [139]:
 ## EX 2   - Reduce 

employees_scores = {'names': ["Arun", "Santhosh", "Vijay", "Sanjay", "Deepak", 
                     "Vasanth", "Vicky", "Akash", "Rahul", "Aditya"],
                    'scores' : ["25","32","19","40","27",
                           "30","31","21","42","24"]}

int_scores = map(int, employees_scores['scores'])
total_sum = reduce(lambda x, y: x + y, int_scores)

print(total_sum)

291