In [4]:
import pandas as pd

In [5]:
sales_final = pd.read_csv("sales_final.csv")
sales_final

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [6]:
sales_final.dtypes

Date           str
Voucher      int64
Party          str
Product        str
Qty          int64
Rate       float64
dtype: object

In [7]:
sales_2017 = pd.read_csv("sales_2017.csv")
sales_2018 = pd.read_csv("sales_2018.csv")
sales_2019 = pd.read_csv("sales_2019.csv")

In [116]:
overral_sales_data = pd.concat(objs=[sales_2017, sales_2018, sales_2019])
overral_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [31]:
overral_sales_data.drop_duplicates(inplace=True)

In [117]:
overral_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [33]:
overral_sales_data['Qty'].convert_dtypes('integer')

0                   2
1                   6
2                 500
3                   6
4                   5
             ...
19169             320
19170             800
19171             400
19174       99,284.90
19175    2,710,193.00
Name: Qty, Length: 96624, dtype: string

In [34]:
overral_sales_data.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

In [35]:
sales_final.dtypes

Date           str
Voucher      int64
Party          str
Product        str
Qty          int64
Rate       float64
dtype: object

In [118]:
overral_sales_data.dtypes

Date              str
Voucher           str
Party             str
Product           str
Qty               str
Rate              str
Gross             str
Disc              str
Voucher Amount    str
dtype: object

In [120]:
overral_sales_data['Voucher'] = overral_sales_data['Voucher'].replace('Sal:','', regex=True)

In [119]:
overral_sales_data ["Voucher"]= overral_sales_data['Voucher'].convert_dtypes('Int64')

In [39]:
sales_final

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [121]:
overral_sales_data['Date'] = pd.to_datetime(overral_sales_data["Date"], format="%d/%m/%Y", errors='coerce')

In [122]:
overral_sales_data["Rate"] = pd.to_numeric(overral_sales_data["Rate"], errors='coerce')

In [123]:
overral_sales_data['Qty'] = pd.to_numeric(overral_sales_data['Qty'], errors='coerce').convert_dtypes('float64')

In [124]:
overral_sales_data["Qty"] = overral_sales_data["Qty"].astype('float64')

In [105]:
overral_sales_data.dtypes

Date           str
Voucher        str
Party          str
Product        str
Qty            str
Rate           str
Gross      float64
dtype: object

In [125]:
overral_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,NaN,"3,380.00",NaN,"13,100.00"
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,NaN,"9,720.00",NaN,NaN
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,"11,500.00",NaN,"30,990.00"
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,NaN,"9,720.00",NaN,NaN
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,NaN,"8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,"6,400.00",NaN,NaN
19172,NaT,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaT,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaT,Total,NaN,NaN,NaN,NaN,"2,203,649.50","20,680.00","2,189,014.50"
19175,NaT,Total,NaN,NaN,NaN,NaN,"53,360,791.40","672,984.00","52,830,224.40"

In [126]:
del overral_sales_data['Disc']

In [127]:
del overral_sales_data['Voucher Amount']

In [129]:
overral_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,NaN,"3,380.00"
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,NaN,"9,720.00"
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,"11,500.00"
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,NaN,"9,720.00"
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,NaN,"8,450.00"
...,...,...,...,...,...,...,...
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,"6,400.00"
19172,NaT,<NA>,NaN,NaN,NaN,NaN,NaN
19173,NaT,<NA>,NaN,NaN,NaN,NaN,NaN
19174,NaT,Total,NaN,NaN,NaN,NaN,"2,203,649.50"
19175,NaT,Total,NaN,NaN,NaN,NaN,"53,360,791.40"

In [134]:
overral_sales_data.drop_duplicates()

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,NaN,"3,380.00"
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,NaN,"9,720.00"
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,"11,500.00"
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,NaN,"9,720.00"
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,NaN,"8,450.00"
...,...,...,...,...,...,...,...
19169,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,"5,120.00"
19170,2019-10-10,4935,K.SRIHARI,10*12 RK,800.0,8.5,"6,800.00"
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,"6,400.00"
19174,NaT,Total,NaN,NaN,NaN,NaN,"2,203,649.50"
19175,NaT,Total,NaN,NaN,NaN,NaN,"53,360,791.40"

In [136]:
overral_sales_data.isnull().sum()

Date       15644
Voucher    12557
Party         40
Product    12591
Qty        19010
Rate       21454
Gross      12558
dtype: int64

In [131]:
sales_final

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [139]:
overral_sales_data['Gross'] = pd.to_numeric(overral_sales_data['Gross'].astype(str).str.replace(',', ''), errors='coerce')

In [115]:
overral_sales_data

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,1/4/2017,<NA>,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00",NaN
1,1/4/2017,<NA>,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00",NaN
2,1/4/2017,<NA>,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,NaN
3,1/4/2017,<NA>,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00",NaN
4,1/4/2017,<NA>,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00",NaN
...,...,...,...,...,...,...,...
19171,10/10/2019,<NA>,K.SRIHARI,13*16 WHITE RK,400,16,NaN
19172,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
19173,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
19174,NaN,<NA>,NaN,NaN,"99,284.90","175,381.65",NaN
19175,NaN,<NA>,NaN,NaN,"2,710,193.00","5,519,888.40",NaN

In [141]:
overral_sales_data['Rate'] = overral_sales_data['Rate'].fillna(overral_sales_data['Gross'] / overral_sales_data['Qty'], inplace=True)

C:\Users\smanoharan\AppData\Local\Temp\ipykernel_3348\1854703355.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  overral_sales_data['Rate'] = overral_sales_data['Rate'].fillna(overral_sales_data['Gross'] / overral_sales_data['Qty'], inplace=True)

In [143]:
overral_sales_data.drop_duplicates()

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0
...,...,...,...,...,...,...,...
19169,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0
19170,2019-10-10,4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0
19174,NaT,Total,NaN,NaN,NaN,NaN,2203649.5
19175,NaT,Total,NaN,NaN,NaN,NaN,53360791.4

In [144]:
overral_sales_data.dropna()

,Date,Voucher,Party,Product,Qty,Rate,Gross
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0
...,...,...,...,...,...,...,...
19167,2019-10-10,4935,K.SRIHARI,16*20(100-W),140.0,26.0,3640.0
19168,2019-10-10,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600.0,8.4,5040.0
19169,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320.0,16.0,5120.0
19170,2019-10-10,4935,K.SRIHARI,10*12 RK,800.0,8.5,6800.0
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400.0,16.0,6400.0

In [170]:
overral_sales_data["Voucher"] = overral_sales_data["Voucher"].str.replace('',"")

In [171]:
overral_sales_data['Voucher'] = pd.to_numeric(overral_sales_data['Voucher'], errors='coerce').convert_dtypes('Int64')

In [152]:
del overral_sales_data['Gross']

In [188]:
overral_sales_data

,Date,Voucher,Party,Product,Qty,Rate
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
19167,2019-10-10,4935,K.SRIHARI,16*20(100-W),140,26.0
19168,2019-10-10,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4
19169,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0
19170,2019-10-10,4935,K.SRIHARI,10*12 RK,800,8.5
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16.0

In [167]:
overral_sales_data.dropna(inplace = True)

In [187]:
sales_final

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [176]:
overral_sales_data['Qty'] = pd.to_numeric(overral_sales_data['Qty'], errors='coerce').convert_dtypes('Int64')

In [185]:
overral_sales_data["Qty"]= overral_sales_data["Qty"].astype('Int64')

In [168]:
sales_final.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
dtype: int64

In [169]:
overral_sales_data.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [186]:
overral_sales_data.dtypes

Date       datetime64[us]
Voucher             Int64
Party                 str
Product               str
Qty                 Int64
Rate              float64
dtype: object

In [184]:
sales_final.dtypes

Date           str
Voucher      int64
Party          str
Product        str
Qty          int64
Rate       float64
dtype: object

In [147]:
overral_sales_data.shape

(111206, 7)

In [149]:
sales_final.isnull().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       1
dtype: int64

In [190]:
overral_sales_data.to_csv("overral_sales_data.csv", index=False)